FROM ubuntu:latest
RUN apt-get update \
    && apt-get install -y git \
    && git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
    && mkdir ~/.linuxbrew/bin \
    && ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin \
    && eval $(~/.linuxbrew/bin/brew shellenv) \
    && brew install gh
