version: "3.9"
services:
  node:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.Node
    volumes:
      - ../src:/usr/app/src
    ports:
      - "3000:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
